### ISSUE TITLE
New sentiment classifier

### ISSUE THREAD

**Issue by woodstr** [hugzito/bachelor_project#23]
We should try to find a pre-trained classifier that is less extreme with its predictions.

**Comment by woodstr** [comment]
Current model is used under "py_files/network_creator.py" in the "create_network" function. More details:

 - Line 153: model is initialized
 - Line 191: model classifies text
 - Line 192: scores are appended to a list called "polarities" (scores range from 0-1 with this classifier)
 - Lines 194-197: "-1" and "1" are appended to a list called "signs" depending on if they are negative or positive sentiment. These values are only used in the "social_balance" notebook for measuring how many frustrated edges there are in the network. Maybe this is another statistic we could use in our table/visualizations? Either way the if statements should relatively easy to tweak to work with any model output.

**Comment by hugzito** [comment]
Models tested: 
- Vader
- HappyTransformer
- Textblob
